Model export vignette
Big-Life-Lab/bllflow pull request #70
Opened 2020-10-07 21:38 UTC by yulric

2020-10-08 02:00 UTC, StaceyFisher commented
1) center.csv - 'finalVariable' is the variable after centering, which may not actually be the final model variable, correct?
2) cox.csv - I assume that I can rename this file, depending on the type of model?
3) model-steps.csv - This file lists the order the files should be run, correct? So 'final' variables from the first file could be an input 'variable' in the second file- that would make sense to me
4) Should dummy variable specification be in another file? Or is it all specified in variable-details.csv? 
5) variable-details.csv - do the columns that are currently empty need to be filled? If so, could you describe what you want in them? I understand the ones that are currently filled
6) variable-details.csv - what variables go in this file? Just variables that need to be dummied? I see you have age as an example, however. Just age? Or also age_c, age_rcs1, and age_rcs2? I suppose maybe it is any variable that should be 'checked' (for min, max ect)? Perhaps it would help if we could specify at what stage this file is used, for example in model-steps.csv?
7) variables.csv - what variables go in this file? all starting variables?

2020-10-08 11:52 UTC, yulric commented
> 
> 
>     1. center.csv - 'finalVariable' is the variable after centering, which may not actually be the final model variable, correct?
> 
>     2. cox.csv - I assume that I can rename this file, depending on the type of model?
> 
>     3. model-steps.csv - This file lists the order the files should be run, correct? So 'final' variables from the first file could be an input 'variable' in the second file- that would make sense to me
> 
>     4. Should dummy variable specification be in another file? Or is it all specified in variable-details.csv?
> 
>     5. variable-details.csv - do the columns that are currently empty need to be filled? If so, could you describe what you want in them? I understand the ones that are currently filled
> 
>     6. variable-details.csv - what variables go in this file? Just variables that need to be dummied? I see you have age as an example, however. Just age? Or also age_c, age_rcs1, and age_rcs2? I suppose maybe it is any variable that should be 'checked' (for min, max ect)? Perhaps it would help if we could specify at what stage this file is used, for example in model-steps.csv?
> 
>     7. variables.csv - what variables go in this file? all starting variables?

1. Yes. Maybe it would be better to rename it to centeredVariable?
2. The fileName does not really matter but the step column value does. For eg., for a logistic regression model we would call the step logistic and the fileName could be model.csv. For the last step, the step column should inform us what kind of the model it is and so what formula needs to be run to evaluate the model.
3. Yes, the transformed variables from one could be inputs to the next file. Essentially, the variables that can be referenced in a file need to declared in some file before it.
4. I'm not sure. Do you think there's some dummying info that is not being captured in the variables-details file? The one good reason to put the dummy info there is because we are also defining the catValues there, so its easy to map a catValue to a dummy variable.
5. Ah sorry, those columns are part of the current variables-details file in cchsflow but I don't think we need them for the model export files. I'll remove them.
6. All the variables defined in the variables.csv file need to be defined in the variables-details file. 
7. All starting variables yes.

2020-10-13 16:48 UTC, StaceyFisher commented
> > ```
> > 1. center.csv - 'finalVariable' is the variable after centering, which may not actually be the final model variable, correct?
> > 
> > 2. cox.csv - I assume that I can rename this file, depending on the type of model?
> > 
> > 3. model-steps.csv - This file lists the order the files should be run, correct? So 'final' variables from the first file could be an input 'variable' in the second file- that would make sense to me
> > 
> > 4. Should dummy variable specification be in another file? Or is it all specified in variable-details.csv?
> > 
> > 5. variable-details.csv - do the columns that are currently empty need to be filled? If so, could you describe what you want in them? I understand the ones that are currently filled
> > 
> > 6. variable-details.csv - what variables go in this file? Just variables that need to be dummied? I see you have age as an example, however. Just age? Or also age_c, age_rcs1, and age_rcs2? I suppose maybe it is any variable that should be 'checked' (for min, max ect)? Perhaps it would help if we could specify at what stage this file is used, for example in model-steps.csv?
> > 
> > 7. variables.csv - what variables go in this file? all starting variables?
> > ```
> 
> 1. Yes. Maybe it would be better to rename it to centeredVariable?
> 2. The fileName does not really matter but the step column value does. For eg., for a logistic regression model we would call the step logistic and the fileName could be model.csv. For the last step, the step column should inform us what kind of the model it is and so what formula needs to be run to evaluate the model.
> 3. Yes, the transformed variables from one could be inputs to the next file. Essentially, the variables that can be referenced in a file need to declared in some file before it.
> 4. I'm not sure. Do you think there's some dummying info that is not being captured in the variables-details file? The one good reason to put the dummy info there is because we are also defining the catValues there, so its easy to map a catValue to a dummy variable.
> 5. Ah sorry, those columns are part of the current variables-details file in cchsflow but I don't think we need them for the model export files. I'll remove them.
> 6. All the variables defined in the variables.csv file need to be defined in the variables-details file.
> 7. All starting variables yes.

1. Yes, I would rename to centeredVariable
4. I think it is fine in the variable-details, as long as we know when dummy-ing occurs, defined in model-steps.csv

I will start to fill these in for DemPoRT.
Thanks!

2020-10-25 14:49 UTC, StaceyFisher commented
@yulric FYI - the vignette is inconsistent with the files. It says interactions are specified in the variable-details file and not in another file, however there it isn't in the example variable details file and there is another file. 
I would prefer the separate file approach

2020-10-25 20:38 UTC, StaceyFisher commented
Baseline hazard should go somewhere too. Not sure where would make the most sense. @yulric

2020-10-26 11:10 UTC, yulric commented
> 
> 
> Baseline hazard should go somewhere too. Not sure where would make the most sense. @yulric

I think in the cox step or in your case the fine-and-grey step. Should we have a row in that file for baseline hazard? I know that some algorithms the baseline hazard changes with time?

2020-10-27 21:20 UTC, DougManuel commented on vignettes/assets/model-export/variables.csv
> +variable,label,labelLong,section,subject,variableType,units,description
The example of variables.csv is the starting variables, not the variables that end up in the model will be transformed. The final variables will be sex_cat1_C_1.

2020-10-27 21:21 UTC, DougManuel commented on vignettes/assets/model-export/variables.csv
> +variable,label,labelLong,section,subject,variableType,units,description
Keep in mind reference population

2020-10-27 21:26 UTC, DougManuel commented on vignettes/assets/model-export/variables-details.csv
> +age,NA,NA,NA,NA,NA,years,cont,"[26,78]",
Keep in mind that max mins will be different from the original variable_details.csv sheet. 

I think we will need outlier treatment in variables or variable details. This method could be in model steps, since outliers is really a transformation.

2020-10-27 21:31 UTC, DougManuel commented on vignettes/assets/model-export/center.csv
> +﻿variable,centerValue,centeredVariable
Suggest that this table look more like a Table 1.

Meaning,
- include some descriptions like median, 95CIs, IQR. 
- stratification will often be needed. eg. sex. 

So, this table be called descriptive.csv or something similar. We don't need to be too prescriptive about what the file contains - could vary by algorithm. 

It could be all or part of the file from RDF.

2020-10-28 09:17 UTC, CBjerke requested changes
@yulric I made a number of edits in the text in a new branch but I can't figure out, in R studio, how to push these changes for your review.

2020-10-28 09:17 UTC, CBjerke commented on vignettes/model-export.Rmd
> +```{r}
Suggest changing catLabel to "D-penicillamine" and keeping catLabelLong "Received D-penicillamine" to better illustrate the difference between details for these two columns

2020-10-28 09:17 UTC, CBjerke commented on vignettes/model-export.Rmd
> +pbc_variables_details <- read.csv(file.path(getwd(), "/assets/model-export/variables-details.csv"))
I also think that the column should be named variableType (as in the variables sheet)

2020-10-28 09:17 UTC, CBjerke commented on vignettes/model-export.Rmd
> +There is no file for the dummy step since we already defined the dummy variables in the variables details file, giving us all the information we need to perform that step.
I think we should provide an example of what would be needed in this file. Perhaps it is better not to simplify the 'status variable' earlier on in the vignette so that details of what would be required could be included here.

2020-10-28 09:17 UTC, CBjerke commented on vignettes/model-export.Rmd
> +The variables sheet gives a summary of all the starting variables used in the model. A brief description of its columns are outlined below,
"Starting" variable is a little confusing, do you really mean this? For example, we would have 'packyears' in this column and not the start variables 'SMKDSTY', 'SMK_01A', etc. Or, do I have this wrong.

2020-10-28 10:46 UTC, DougManuel requested changes
I really like how you've walked through an example of the whole algorithm development. 

A few overarching comments:
1) The **primary purpose of export** is to provide information to allow other to calculate risk using our API, their own implementation, etc. Right? I think we can have other documentation if people want to recreate the entire algorithm development process. Or the model export is part of the overall development to implementation to validation process.

2) **Model description** - We'll need overall model information: algorithm name, creator, etc. We originally had this information on a google sheet and then we've started to develop the config file. the config file is the way to go, but it has quite a bit of information that we would not need for model export. 

3) **variables.csv** the key information is, _I think_ final variables, not starting variables. For discussion. I think we may want to have three types of variables.
- final variables - the exact final variables that are used to estimate the algorithm. This would basically be a description of any variable that has a beta coefficient. There should be a one-to-one-match with beta coefficients. We have labels, etc. for every variable in the beta sheet.
- starting variables from our development data - I actually don't think this is as important, but we need for batch mode.
- starting variables for LIME or our web implementation. Again, not as important for many people, but I think helpful for ourselves and others.
- we probably don't need to include other implementations (say St. Vincent, for RESPECT) but this is a consideration. We probably want separate documentation for specific implementation in a setting like St. V.

4) **Metadata** - we need a file to describe the variables headers in this documentation definitions for such things as 'coefficient', rcsVariables, knots, centreVariable, etc. This could be a separate reference file that we use for multiple models. If so, this reference file needs to be in the model description file with a version of the metadata (since it will change). We've started this metadata in a few places, including google sheets and @DarkShadeKnigh R code within bllflow.

2020-10-28 10:49 UTC, DougManuel commented
I've added @Rhan43 to this PR review, since she'll need to create oversee the creation of model export for RESPECT. Also included @amytmhsu in case she want to see what's going on.

2020-10-28 11:53 UTC, yulric commented on vignettes/assets/model-export/variables.csv
> +variable,label,labelLong,section,subject,variableType,units,description
Yes, the variables.csv files should document all the variables that are not part of any subsequent step in the algorithm. For eg., you would not put the RCS variables in here because they would be documented in the RCS file.

2020-10-28 11:55 UTC, yulric commented on vignettes/assets/model-export/center.csv
> +﻿variable,centerValue,centeredVariable
This file is not a descriptive table for the variables but to document how to center certain variables in the algorithm.

2020-10-28 11:57 UTC, yulric commented on vignettes/model-export.Rmd
> +The variables sheet gives a summary of all the starting variables used in the model. A brief description of its columns are outlined below,
Yes, thinking now I believe this file should include all the variables in the algorithm that are not part of any other step file.

2021-10-22 17:41 UTC, Rhan43 reviewed
For discussion: we've listed files specific to this specific stage "describing a model". However, I'm still not 100% clear how these files fit relative to other files along the entire process: initial specification to web implementation. Ideally, we'd have one file to use at each stage its needed. 
As I mentioned in a comment variables and variable_detials are used to describe two different stages: "prespecifying your data" and "describing your prediction model", however the details required for each file is currently different for each stage.
Also a potential issue, is with "describing your prediction model" and "implementing to web". In "describing your prediction model" we ask for a center.csv, but in implementing to web, we also use the centering values to deal with errors (e.g., input value is missing).

2023-04-04 13:44 UTC, yulric commented
Closing PR. All documentation is in the [model parameters repo](https://github.com/Big-Life-Lab/model-parameters).

2023-04-04 13:44 UTC, closed without merging